[package]
name = "majjit"
version = "0.1.0"
edition = "2024"
rust-version = "1.95.0"

[dependencies]
ansi-to-tui = "8.0.1"
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
crossterm = "0.29.0"
fuzzy-matcher = "0.3.7"
indexmap = "2.14.0"
ratatui = "0.30.2"
ratatui-textarea = "0.9.2"
regex = "1.13.1"
shell-words = "1.1.1"
tempfile = "3.27.0"
terminal-colorsaurus = "1.0.3"
tokio = { version = "1.53.1", features = ["macros", "rt", "sync"] }
watchman_client = "0.9.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
